apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: davp-demo13
  janus-idp.io/tekton: davp-demo13
  backstage.io/kubernetes-id: davp-demo13
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: davp-demo13
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
